const id = new URLSearchParams(location.search).get("practice") || "P-2026-LIPE-001";
const $ = (selector) => document.querySelector(selector);
const labels = {DA_FARE:"Da fare",IN_LAVORAZIONE:"In corso",COMPLETATO:"Completato",COMPLETATA:"Completata",DA_VALIDARE:"Da validare",VALIDATA:"Validata",CHIUSA:"Chiusa"};
const italianDate = (value) => new Intl.DateTimeFormat("it-IT", {day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`));
async function request(path, options) { const response=await fetch(path,options); const data=await response.json(); if(!response.ok) throw new Error(data.error||"Operazione non riuscita"); return data; }
function esc(value){const n=document.createElement("span");n.textContent=value??"";return n.innerHTML}
function evidenceHtml(item){const meta=[item.document_type,item.description,item.actor,item.created_at?new Date(item.created_at).toLocaleString('it-IT'):""].filter(Boolean).join(" · ");return `<span class="doc-preview"><a class="doc-icon" href="${item.preview_url}" target="_blank" title="${esc(meta)}">📄 ${esc(item.filename)}</a><span class="doc-popover"><span>${esc(meta||item.content_type||"Documento")}</span><a href="${item.preview_url}" target="_blank">Apri anteprima</a></span></span>`}
function completionClass(result){if(!result)return "";return result.outcome==="CON_RILIEVI"||String(result.outcome).includes("RILIEVI")?"completed-warning":"completed-ok"}
function render(practice) {
  $("#practice-id").textContent=practice.id; if($("#practice-title")) $("#practice-title").textContent=`${practice.practice_type_code} · ${practice.client_id}`; if($("#practice-type")) $("#practice-type").textContent=practice.practice_type_code; $("#client").textContent=practice.client_id; $("#due").textContent=italianDate(practice.due_date);
  $("#manager").textContent=practice.roles.manager; $("#validator").textContent=practice.roles.validator; $("#period").textContent=`${italianDate(practice.period_start)} – ${italianDate(practice.period_end)}`; $("#status").textContent=labels[practice.status]||practice.status;
  $("#progress").textContent=`${practice.progress.completed} / ${practice.progress.total}`; $("#bar").style.width=`${100*practice.progress.completed/practice.progress.total}%`;
  const resultById=Object.fromEntries(practice.results.map(result=>[result.id,result]));
  $("#tasks").innerHTML=practice.tasks.map(task=>{const result=task.result_id?resultById[task.result_id]:null,done=task.status==='COMPLETATO',reopened=Boolean(task.reopen_reason);const title=`<a class="task-open-link" href="/manager-task.html?practice=${encodeURIComponent(practice.id)}&task=${encodeURIComponent(task.code)}">${esc(task.title)}</a>`;const work=task.status==='IN_LAVORAZIONE'&&task.work_note?` · nota di lavoro: ${esc(task.work_note)}`:"";const reopen=reopened?` · riaperto: ${esc(task.reopen_reason)}`:"";const stateClass=done?completionClass(result):reopened?'reopened-task':task.status==='IN_LAVORAZIONE'?'in-progress':'';const stateIcon=done?'✓':reopened?'↻':task.status==='IN_LAVORAZIONE'?'…':'';return `<div class="task ${done?'done':''} ${stateClass}"><span class="check">${stateIcon}</span><div><div class="task-code">${task.code} · ${labels[task.status]||task.status}</div><div class="task-title">${title}</div><small>Assegnato a <strong>${task.assignee}</strong>${task.completed_by?` · completato da <strong>${task.completed_by}</strong>`:''}${task.depends_on.length?` · dipende da ${task.depends_on.join(', ')}`:' · nessuna dipendenza'}${work}${reopen}</small></div><div>${!done?`<select data-assignee="${task.code}"><option ${task.assignee==='anna.operatore'?'selected':''}>anna.operatore</option><option ${task.assignee==='luca.operatore'?'selected':''}>luca.operatore</option></select>`:''}</div></div>`}).join("");
  document.querySelectorAll("[data-assignee]").forEach(select=>select.onchange=()=>assign(select.dataset.assignee,select.value)); $("#close").disabled=practice.status!=="VALIDATA";
  const evidenceById=Object.fromEntries(practice.evidence.map(item=>[item.id,item]));
  const taskByCode=Object.fromEntries(practice.tasks.map(task=>[task.code,task]));
  $("#results").innerHTML=practice.results.length?practice.results.map(result=>{const task=result.related_task_code?taskByCode[result.related_task_code]:null;const current=task&&task.result_id===result.id;const historical=task&&!current;const heading=result.related_task_code?`${result.related_task_code} · ${esc(task?.title||'Task')} · ${esc(result.outcome)}`:`${result.action} · ${esc(result.outcome)}`;const badge=historical?` <span class="history-badge">STORICO</span>`:"";const linked=result.evidence_ids.map(eid=>evidenceById[eid]).filter(Boolean);return `<div class="result"><strong>${heading}${badge}</strong><p>${esc(result.note||"Nessuna nota")}</p><small>${esc(result.actor)} (${result.actor_role}) · ${new Date(result.timestamp).toLocaleString('it-IT')}</small>${linked.length?`<div class="evidence-list">${linked.map(evidenceHtml).join("")}</div>`:`<div class="evidence-list empty-evidence">Nessun allegato associato a questo risultato.</div>`}</div>`}).join(""):"<p>Nessun risultato registrato.</p>";
  const practiceEvidence=practice.evidence.filter(item=>!item.related_task_code);
  $("#evidence").innerHTML=practiceEvidence.length?`<div class="practice-evidence"><h3>Documenti di pratica</h3><div class="evidence-list">${practiceEvidence.map(evidenceHtml).join("")}</div></div>`:"";
  $("#audit").innerHTML=practice.audit.slice(0,14).map(event=>`<div class="event"><strong>${event.event_type.replaceAll('_',' ')}</strong><span>${event.actor} · ${new Date(event.at).toLocaleString('it-IT')}</span></div>`).join("");
}
async function assign(task, assignee) { try { render(await request(`/api/practices/${id}/tasks/${task}/assign`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actor:"marta.manager",assignee})})); } catch(error) { $("#message").textContent=error.message; $("#message").hidden=false; } }
$("#close").onclick=async()=>{const attachments=[];try{$("#message").hidden=true;render(await request(`/api/practices/${id}/close`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actor:"marta.manager",outcome:$("#close-outcome").value,note:$("#close-note").value,attachments})}))}catch(error){$("#message").textContent=error.message;$("#message").hidden=false}};
request(`/api/practices/${id}`).then(render).catch(error=>{ $("#message").textContent=error.message; $("#message").hidden=false; });
