const ENTITY_META={
 users:{title:'Utenti',fields:[['id','ID'],['username','Login'],['display_name','Nome visualizzato'],['default_membership_id','Appartenenza predefinita']]},
 groups:{title:'Gruppi',fields:[['id','Codice'],['name','Nome'],['role','Ruolo']]},
 memberships:{title:'Appartenenze',fields:[['id','ID'],['user_id','Utente'],['group_id','Gruppo'],['label','Etichetta']]},
 assignment_policies:{title:'Politiche di assegnazione',fields:[['id','Codice'],['name','Nome'],['strategy','Strategia'],['description','Descrizione']]},
 practice_types:{title:'Tipi di pratica',fields:[['id','ID'],['code','Codice'],['name','Nome'],['description','Descrizione']]}
};
let configData=null;let currentEntity='groups';
async function api(url,options){const r=await fetch(url,options);const p=await r.json();if(!r.ok)throw new Error(p.error||'Operazione non riuscita');return p;}
async function load(){configData=await api('/api/admin/config');renderNav();renderTable();}
function renderNav(){document.querySelectorAll('[data-entity]').forEach(b=>{b.disabled=false;b.classList.toggle('active',b.dataset.entity===currentEntity);b.onclick=()=>{currentEntity=b.dataset.entity;renderTable();};});}
function rows(){return configData[currentEntity]||[];}
function lookup(entity,id,field){const r=(configData[entity]||[]).find(x=>x.id===id);return r?(r[field]||id):id||'';}
function displayValue(field,value){if(field==='user_id')return lookup('users',value,'display_name');if(field==='group_id')return lookup('groups',value,'name');return value??'';}
function renderTable(){const meta=ENTITY_META[currentEntity];document.getElementById('cfg-title').textContent=meta.title;const head=document.getElementById('cfg-head');const body=document.getElementById('cfg-body');head.innerHTML='<tr>'+meta.fields.map(f=>`<th>${f[1]}</th>`).join('')+'<th>Stato</th><th>Azioni</th></tr>';body.innerHTML='';for(const row of rows()){const tr=document.createElement('tr');tr.innerHTML=meta.fields.map(f=>`<td>${escapeHtml(String(displayValue(f[0],row[f[0]])))}</td>`).join('')+`<td>${row.active===false?'Disattivo':'Attivo'}</td><td><button data-edit>Modifica</button> <button data-delete>Elimina</button></td>`;tr.querySelector('[data-edit]').onclick=()=>openEditor(row);tr.querySelector('[data-delete]').onclick=()=>removeItem(row);body.appendChild(tr);}document.getElementById('cfg-empty').hidden=rows().length>0;}
function selectHtml(name,label,options,value){return `<label>${label}<select name="${name}">${options.map(o=>`<option value="${escapeAttr(o.value)}" ${o.value===value?'selected':''}>${escapeHtml(o.label)}</option>`).join('')}</select></label>`;}
function openEditor(row={}){const meta=ENTITY_META[currentEntity];const form=document.getElementById('cfg-form');const editing=!!row.id;document.getElementById('editor-title').textContent=(editing?'Modifica ':'Nuovo ')+meta.title.toLowerCase();let html='';for(const [name,label] of meta.fields){if(currentEntity==='groups'&&name==='role'){html+=selectHtml(name,label,(configData.roles||[]).map(x=>({value:x,label:x})),row[name]||'OPERATORE');continue;}if(currentEntity==='memberships'&&name==='user_id'){html+=selectHtml(name,label,(configData.users||[]).map(x=>({value:x.id,label:x.display_name})),row[name]||'');continue;}if(currentEntity==='memberships'&&name==='group_id'){html+=selectHtml(name,label,(configData.groups||[]).map(x=>({value:x.id,label:x.name})),row[name]||'');continue;}const textarea=name==='description';html+=`<label>${label}${textarea?`<textarea name="${name}">${escapeHtml(row[name]||'')}</textarea>`:`<input name="${name}" value="${escapeAttr(row[name]||'')}" ${editing&&name==='id'?'readonly':''}>`}</label>`;}html+=`<label class="check"><input type="checkbox" name="active" ${row.active===false?'':'checked'}> Attivo</label><div class="dialog-actions"><button type="button" id="cfg-cancel">Annulla</button><button type="submit">Salva</button></div>`;form.innerHTML=html;form.onsubmit=saveItem;document.getElementById('cfg-cancel').onclick=()=>document.getElementById('cfg-dialog').close();document.getElementById('cfg-dialog').showModal();}
async function saveItem(ev){ev.preventDefault();const fd=new FormData(ev.currentTarget);const item=Object.fromEntries(fd.entries());item.active=fd.has('active');try{await api(`/api/admin/config/${currentEntity}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});document.getElementById('cfg-dialog').close();await load();}catch(e){alert(e.message);}}
async function removeItem(row){if(!confirm(`Eliminare ${row.name||row.display_name||row.label||row.id}?`))return;try{await api(`/api/admin/config/${currentEntity}/delete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});await load();}catch(e){alert(e.message);}}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function escapeAttr(s){return escapeHtml(String(s));}
document.getElementById('cfg-new').onclick=()=>openEditor({active:true});load().catch(e=>{document.getElementById('cfg-error').textContent=e.message;});
