const list=document.querySelector('#practice-list'),message=document.querySelector('#message');
const esc=value=>{const n=document.createElement('span');n.textContent=value??'';return n.innerHTML};
const date=value=>new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T00:00:00`));
const labels={DA_FARE:'Da fare',IN_LAVORAZIONE:'In corso',COMPLETATA:'Completata',DA_VALIDARE:'Da validare',VALIDATA:'Validata',NON_VALIDATA:'Non validata'};
function health(p){if(p.status==='NON_VALIDATA'||p.urgency.level==='OVERDUE')return 'problem';if(p.situation.code==='WARNINGS')return 'warning';if(p.status==='DA_FARE')return 'neutral';return 'ok'}
function situation(p){if(p.status==='NON_VALIDATA')return '<span class="situation-badge situation-problem">Non validata</span>';if(p.situation.code==='WARNINGS')return `<span class="situation-badge situation-warning">${esc(p.situation.label)}</span>`;return '<span class="situation-badge situation-ok">Regolare</span>'}
function progress(p){const pct=Math.max(0,Math.min(100,Number(p.progress.percent)||0));return `<span class="progress-cell"><span class="progress-donut" style="--progress:${pct*3.6}deg"><span>${p.progress.completed}/${p.progress.total}</span></span><small>${pct}%</small></span>`}
function row(p){return `<a class="practice-list-row health-${health(p)} urgency-${String(p.urgency.level).toLowerCase()}" href="/practice.html?practice=${encodeURIComponent(p.id)}"><span><strong>${esc(p.client_id)}</strong></span><span><strong>${esc(p.practice_type_code)}</strong><small>${esc(p.id)}</small></span><span>${date(p.period_start)} – ${date(p.period_end)}</span><span><strong>${date(p.due_date)}</strong></span><span><span class="practice-state state-${String(p.status).toLowerCase()}">${esc(labels[p.status]||p.status)}</span></span>${progress(p)}<span>${situation(p)}</span><span><strong>${esc(p.urgency.label)}</strong><small>${esc(p.urgency.detail)}</small></span></a>`}
fetch('/api/manager/practices?actor=marta.manager').then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'Errore');list.innerHTML=data.length?data.map(row).join(''):'<p class="empty-list">Nessuna pratica attiva.</p>'}).catch(error=>{message.textContent=error.message;message.hidden=false});
